@echo off
echo Runing tool remove bloatware fujitsu arrows we
adb devices
pause
for %%X in (
jp.co.softbank.wispr.froyo
jp.radiko.radio.player
com.fujitsu.mobile_phone.fjpedometerservice
jp.softbank.mb.xcap
jp.softbank.tether.entitlement
jp.softbank.mb.datamigration
jp.co.yahoo.android.yshopping
jp.softbank.mb.parentalcontrols
jp.softbank.mb.plusmessage
jp.softbank.mb.fivegservice
jp.co.yahoo.android.yjtop
com.aura.oobe.softbank
com.fcnt.mobile_phone.gamegallery
com.fcnt.mobile_phone.powersavingservice5g
com.fcnt.mobile_phone.gamelauncher
com.fcnt.overlay.phoneapp.frameworkres.sbm
com.fcnt.mobile_phone.dataautoselect
com.fcnt.overlay.phoneapp.carrierconfig.sbm
com.fcnt.mobile_phone.fcntmodeprovider
com.fcnt.mobile_phone.update_disallowapp
com.fcnt.mobile_phone.arrowswallet
com.fcnt.overlay.phoneapp.telecom.common
com.fcnt.mobile_phone.fcntsarservice
com.fcnt.overlay.phoneapp.telephony.sbm
com.fcnt.overlay.phoneapp.telephony.common
com.fcnt.overlay.phoneapp.phoneappex.common
com.fcnt.mobile_phone.phoneappcallscreening
com.fcnt.mobile_phone.gamemode
com.fcnt.mobile_phone.meetingmode
com.fcnt.mobile_phone.rakurakucommunity
com.fcnt.EuiccOverlayApp
com.fcnt.mobile_phone.phoneappfakecall
com.fcnt.overlay.phoneapp.dialer.common
com.fcnt.mobile_phone.fastmemo
com.fcnt.mobile_phone.phoneappprivacynumberssetting
com.fcnt.mobile_phone.wifi.resources
com.fcnt.overlay.phoneapp.phoneappex.sbm
com.fcnt.mobile_phone.collectdevicelog
com.fcnt.mobile_phone.wifiservice
com.fcnt.mobile_phone.privacymodesettings
com.fcnt.mobile_phone.oemconfigobserver
com.fcnt.mobile_phone.sitechecker
com.fcnt.mobile_phone.fcntappdownloader
com.fcnt.mobile_phone.lamembers
com.fcnt.mobile_phone.providers.photos
com.fcnt.overlay.phoneapp.carrierconfig.common
com.fcnt.overlay.phoneapp.settings.common
com.fcnt.mobile_phone.privacymodeservice
com.fcnt.mobile_phone.tethering.overlay
com.fujitsu.mobile_phone.phonebookeasymovingservice
com.fujitsu.mobile_phone.healthcare
com.fujitsu.overlay.bluetooth
com.fujitsu.mobile_phone.StartupWizard
com.fujitsu.mobilephone.settings
com.fujitsu.mobile_phone.fjextendedcontacts
com.fujitsu.mobile_phone.voicememo
com.fujitsu.mobile_phone.fjtemperatureserver
com.fujitsu.mobile_phone.fjgsuwcustomapp
com.fujitsu.mobile_phone.fjpedometerservice
com.fujitsu.overlay.documentsui
com.fujitsu.mobile_phone.OpeningHome
com.fujitsu.mobile_phone.colorthemeblack
com.fujitsu.mobile_phone.fjfrauddetectservice
com.fujitsu.mobile_phone.ArrowsSetting
com.fujitsu.mobile_phone.CaptivePortalSettings
com.fujitsu.overlay.systemui
com.fujitsu.overlay.wallpapercropper
com.fujitsu.mobile_phone.fjjuniormode
com.fujitsu.mobile_phone.OneTouchBuzzer
com.fujitsu.mobile_phone.callmemo
com.fujitsu.overlay.frameworkres
com.fujitsu.mobile_phone.colorthemewhite
com.fujitsu.mobile_phone.textcopyatanyscreen
com.fujitsu.mobile_phone.TransferSupport
com.fujitsu.overlay.inputdevices
com.fujitsu.mobile_phone.Araikata
com.fujitsu.mobile_phone.easycontacts
com.fujitsu.mobile_phone.fjserver
com.fujitsu.mobile_phone.SelectHomeScreen
com.fujitsu.mobile_phone.colorthemeturquoise
com.fujitsu.mobile_phone.HumanCentricSettings
com.fujitsu.mobile_phone.SimpleClockWidget
com.fujitsu.mobile_phone.fjhome_simple
com.fujitsu.overlay.carrierconfig
com.fujitsu.mobile_phone.OwnStateSettings
com.fujitsu.mobile_phone.easydialer
com.fujitsu.mobile_phone.fjhce
com.fujitsu.mobile_phone.slideinlauncher
com.fujitsu.mobile_phone.NXwidget
com.fujitsu.mobile_phone.MusicPicker
com.fujitsu.mobile_phone.clearfontsettings
com.fujitsu.mobile_phone.fjjuniormodeprovider
com.fujitsu.mobile_phone.passwordmanager
com.fujitsu.mobile_phone.android.hardware.liedownanalysis
com.fujitsu.mobile_phone.lowmemory
com.fujitsu.mobile_phone.screenmemo
com.fujitsu.mobile_phone.WeatherWidget
com.fujitsu.overlay.settings
com.fujitsu.mobile_phone.onetouchdial
com.fujitsu.mobile_phone.log.aac
com.fujitsu.mobile_phone.simplemode
com.fujitsu.mobile_phone.Recommend
com.fujitsu.mobile_phone.camera
com.fujitsu.mobile_phone.provider
com.fujitsu.mobile_phone.legiblefont
com.fujitsu.mobile_phone.phoneappex
com.fujitsu.mobile_phone.ArrowsSetting
com.fujitsu.mobile_phone.passwordmanager
com.fcnt.mobile_phone.lamembers
com.fujitsu.mobile_phone.phoneappex
jp.softbank.mb.dmb
com.fujitsu.mobile_phone.TransferSupport
com.fcnt.mobile_phone.fastmemo
com.fcnt.mobile_phone.arrowswallet
com.fujitsu.mobile_phone.Recommend
com.google.android.apps.nbu.files
com.fcnt.mobile_phone.gamelauncher
com.fcnt.mobile_phone.gamemode
com.fcnt.mobile_phone.gamegallery
com.google.android.googlequicksearchbox
com.google.android.videos
com.fujitsu.mobile_phone.Araikata
com.fujitsu.mobile_phone.healthcare
com.google.android.apps.tachyon
jp.co.softbank.OfficialApp
com.felicanetworks.mfm.main
com.felicanetworks.mfw.a.boot
com.felicanetworks.mfs
com.adobe.psmobile
jp.softbank.mb.cbrl
jp.co.yahoo.android.yjtop
com.google.android.apps.youtube.music
com.fcnt.mobile_phone.rakurakucommunity
com.fcnt.mobile_phone.fcntappdownloader
com.google.ar.core
com.fujitsu.mobile_phone.fjjuniormodeprovider
com.fujitsu.mobile_phone.fjjuniormode
com.fcnt.mobile_phone.privacymodesettings
com.fcnt.mobile_phone.privacymodeservice
com.fujitsu.mobile_phone.textcopyatanyscreen
jp.radiko.radio.player
com.fujitsu.mobile_phone.fjpedometerservice
com.fcnt.mobile_phone.fcntsarservice
com.fcnt.mobile_phone.sitechecker
com.facebook.katana
com.fujitsu.mobile_phone.simplemode
com.fujitsu.mobile_phone.clearfontsettings
com.fujitsu.mobile_phone.screenmemo
com.fujitsu.mobile_phone.legiblefont
com.fujitsu.mobile_phone.voicememo
com.fujitsu.mobile_phone.slideinlauncher
com.fcnt.mobile_phone.meetingmode
com.fujitsu.mobile_phone.SimpleClockWidget
com.atok.mobile.im.fujitsu.theme.flicklearning
com.atok.mobile.im.fujitsu.theme.black
com.atok.mobile.im.fujitsu.service
com.atok.mobile.im.fujitsu.theme.basic
com.atok.mobile.im.fujitsu.theme.model.po
com.atok.mobile.im.fujitsu.dictionary
com.atok.mobile.im.fujitsu.theme.model.rakuraku
com.atok.mobile.im.fujitsu.theme.custom2
com.atok.mobile.im.fujitsu.theme.custom1
com.atok.mobile.im.fujitsu.theme.model.aq
com.atok.mobile.im.fujitsu.theme.white
com.atok.mobile.im.fujitsu.theme.model.ga
com.atok.mobile.im.fujitsu.theme.model.simple
com.atok.mobile.im.fujitsu.theme.model.el
com.atok.mobile.im.fujitsu.theme.model.fpd
com.fujitsu.mobile_phone.onetouchdial
com.fujitsu.mobile_phone.easycontacts
com.fujitsu.mobile_phone.easydialer
com.fujitsu.mobile_phone.phonebookeasymovingservice
com.fujitsu.mobile_phone.fjhome_simple
com.fujitsu.mobile_phone.NXwidget
com.fujitsu.mobile_phone.callmemo
com.fujitsu.mobile_phone.WeatherWidget
com.aura.oobe.softbank
jp.softbank.mb.bizlock
jp.softbank.mb.ichinaviclt
com.google.android.gm
com.google.android.calendar
com.android.providers.calendar
com.google.android.apps.restore
com.google.android.apps.wellbeing
com.google.android.as
com.google.android.setupwizard
com.android.bookmarkprovider
com.google.android.health.connect.backuprestore
com.google.android.healthconnect.controller
com.android.providers.partnerbookmarks
com.google.android.tag
com.android.providers.userdictionary
com.google.android.as.oss
com.felicanetworks.mfc
com.facebook.system
com.facebook.appmanager
com.facebook.services
com.android.providers.downloads.ui
com.google.android.projection.gearhead
com.google.android.marvin.talkback
com.android.dreams.phototable
com.android.wallpaper.livepicker
com.atok.mobile.im.fujitsu.theme.model.ip
com.android.stk
com.google.android.cellbroadcastreceiver
com.google.android.adservices.api
com.google.android.partnersetup
com.google.ambient.streaming
 ) do (
    adb shell pm disable-user %%X
    adb shell am force-stop %%X
    adb shell pm clear %%X
)
pause